basic setup of tools (phpcs, phpstan, phpunit) in php library
BrandEmbassy/query-language-parser pull request #1
Opened 2020-12-28 15:28 UTC by janveselynet

2021-01-06 08:56 UTC, dominikvoda commented on examples/Car/CarCollection.php
> +     * @var array|Car[]
```suggestion
     * @var array<int, Car>
```

2021-01-06 09:16 UTC, dominikvoda commented on src/Operator/GreaterThan/QueryLanguageFieldSupportingGreaterThanOperator.php
> +     * @param mixed $value     output of single value parser
wrong alignment

2021-01-06 09:18 UTC, dominikvoda commented on src/Operator/NotIn/QueryLanguageFieldSupportingNotInOperator.php
> +     * @param mixed[] $values    output of multiple values parser
wrong alignment

2021-01-06 09:21 UTC, dominikvoda approved these changes

2021-01-06 18:06 UTC, abcondas commented on examples/Car/Car.php
> +        return $this->color !== null;
what if the color = '' (blank string)?

2021-01-06 18:49 UTC, abcondas commented on src/Operator/EqualTo/QueryLanguageFieldSupportingEqualToOperator.php
> +     * @param mixed $value     output of single value parser
wrong alignment

2021-01-06 18:54 UTC, abcondas commented on src/Operator/GreaterThan/GreaterThanQueryLanguageOperator.php
> +            }
$operator is not used in this function

2021-01-06 19:26 UTC, abcondas commented on src/Operator/GreaterThanOrEqualTo/GreaterThanOrEqualToQueryLanguageOperator.php
> +            }
$operator is not used in this static function...

2021-01-06 22:15 UTC, abcondas commented on src/Operator/In/InQueryLanguageOperator.php
> +        );
$operator not used in static function...

2021-01-06 22:40 UTC, abcondas commented on src/Operator/In/InQueryLanguageOperatorTest.php
> +    }
what about a 2-word brand?  I don't think this will work even if you put double-quotes around "Alfa Romeo"...
`
'expectedBrands' => ['Alfa Romeo'],
'query' => 'brand IN (Alfa Romeo)'
`

2021-01-06 22:43 UTC, abcondas commented on src/Operator/In/QueryLanguageFieldSupportingInOperator.php
> +     *
wrong alignment

2021-01-06 22:49 UTC, abcondas commented on src/Operator/IsNotNull/IsNotNullQueryLanguageOperator.php
> +            }
$operator param not needed

2021-01-06 23:01 UTC, abcondas commented on src/Operator/IsNull/IsNullQueryLanguageOperator.php
> +                return $field->createIsNullOperatorOutput($identifier);
$operator not needed

2021-01-06 23:02 UTC, abcondas commented on src/Operator/LessThan/LessThanQueryLanguageOperator.php
> +            }
$operator not needed

2021-01-06 23:05 UTC, abcondas commented on src/Operator/LessThan/QueryLanguageFieldSupportingLessThanOperator.php
> +     *
alignment

2021-01-06 23:07 UTC, abcondas commented on src/Operator/LessThanOrEqualTo/LessThanOrEqualToQueryLanguageOperator.php
> +            }
$operator not needed

2021-01-06 23:08 UTC, abcondas commented on src/Operator/LessThanOrEqualTo/QueryLanguageFieldSupportingLessThanOrEqualToOperator.php
> +     * @param mixed $value     output of single value parser
alignment

2021-01-06 23:09 UTC, abcondas commented on src/Operator/NotEqualTo/NotEqualToQueryLanguageOperator.php
> +            }
$operator not needed

2021-01-06 23:14 UTC, abcondas commented on src/Operator/NotEqualTo/NotEqualToQueryLanguageOperatorTest.php
> +    }
again, will a 2-word brand work?  'Alfa Romeo'?

2021-01-06 23:15 UTC, abcondas commented on src/Operator/NotEqualTo/QueryLanguageFieldSupportingNotEqualToOperator.php
> +     *
alignment

2021-01-06 23:17 UTC, abcondas commented on src/Operator/NotIn/NotInQueryLanguageOperator.php
> +        );
probably should add data types to all of these static functions.
$operator not needed

2021-01-06 23:17 UTC, abcondas commented on src/Operator/NotIn/NotInQueryLanguageOperatorTest.php
> +        ];
test 2-word brand - 'Alfa Romeo'

2021-01-07 18:03 UTC, abcondas commented on src/Value/MultipleValuesExpressionParserCreator.php
> +                ),
would be nicer if these 2 values (0, null) were each put into a named constant so it's easy to tell what they are for (self-documenting).

2021-01-07 18:04 UTC, abcondas commented on src/Value/MultipleValuesExpressionParserCreator.php
> +            }
$openBracket & $closeBracket not needed in function

2021-01-07 18:05 UTC, abcondas commented on src/Value/MultipleValuesExpressionParserCreatorTest.php
> +            ],
2-word brand?  'Alfa Romeo'

2021-01-07 18:07 UTC, abcondas commented on src/Value/MultipleValuesExpressionParserCreatorTest.php
> +            ['multipleValueExpression' => 'hello world'],
so, does this mean that a 2-word brand would not be allowed?  seems so...

2021-01-07 18:11 UTC, abcondas commented on src/Value/PositiveIntegerValueParserCreator.php
> +            '#^[1-9][0-9]*#',
place this in a constant (as is consistently done throughout the rest of the code)

2021-01-07 18:11 UTC, abcondas commented on src/Value/StringValueParserCreator.php
> +            static function ($value): string {
place in constant

2021-01-07 18:13 UTC, abcondas requested changes
Just a few updates needed.

2021-02-01 08:24 UTC, janveselynet commented on src/Operator/GreaterThan/GreaterThanQueryLanguageOperator.php
> +            }
It must be there because the parser library is sending all parts of the parsed text into the callback function.

2021-02-01 08:24 UTC, janveselynet commented on src/Operator/GreaterThanOrEqualTo/GreaterThanOrEqualToQueryLanguageOperator.php
> +            }
As above

2021-02-01 08:24 UTC, janveselynet commented on src/Operator/In/InQueryLanguageOperator.php
> +        );
As above

2021-02-01 08:24 UTC, janveselynet commented on src/Operator/IsNotNull/IsNotNullQueryLanguageOperator.php
> +            }
As above

2021-02-01 08:24 UTC, janveselynet commented on src/Operator/IsNull/IsNullQueryLanguageOperator.php
> +                return $field->createIsNullOperatorOutput($identifier);
As above

2021-02-01 08:25 UTC, janveselynet commented on src/Operator/LessThan/LessThanQueryLanguageOperator.php
> +            }
As above

2021-02-01 08:25 UTC, janveselynet commented on src/Operator/LessThanOrEqualTo/LessThanOrEqualToQueryLanguageOperator.php
> +            }
As above

2021-02-01 08:25 UTC, janveselynet commented on src/Operator/NotEqualTo/NotEqualToQueryLanguageOperator.php
> +            }
As above

2021-02-01 08:26 UTC, janveselynet commented on src/Value/MultipleValuesExpressionParserCreator.php
> +            }
As above

2021-02-01 08:32 UTC, janveselynet commented on src/Operator/In/InQueryLanguageOperatorTest.php
> +    }
Yeah, you are right, it won't work in the current code. But for simplicity of the example, I leave brand name (and also color) only as string value without spaces and not wrapped in quotes.

Once you will be using query language parser to implement your own query language (eg. message search query language) you can define your own value parser for each field - and this parser can take into account quotes, spaces etc. - it's completely on the one implementing the certain query language.

2021-02-01 08:33 UTC, janveselynet commented on src/Operator/NotEqualTo/NotEqualToQueryLanguageOperatorTest.php
> +    }
As above

2021-02-01 08:33 UTC, janveselynet commented on src/Operator/NotIn/NotInQueryLanguageOperatorTest.php
> +        ];
As above

2021-02-01 08:33 UTC, janveselynet commented on src/Value/MultipleValuesExpressionParserCreatorTest.php
> +            ],
As above

2021-02-01 08:33 UTC, janveselynet commented on src/Value/MultipleValuesExpressionParserCreatorTest.php
> +            ['multipleValueExpression' => 'hello world'],
Yeah, it's not. More detailed description above.

2021-02-01 09:09 UTC, janveselynet commented on src/Operator/NotIn/NotInQueryLanguageOperator.php
> +        );
The problem of data types here is that they are flexible because it's the value that your field parser or value parser returns. So in this case I think it's not possible to specify narrower data types for these values.

2021-02-01 18:11 UTC, abcondas commented on src/Operator/EqualTo/QueryLanguageFieldSupportingEqualToOperator.php
> +     * @param mixed $value soutput of single value parser
soutput?  why the 's'?

2021-02-01 18:12 UTC, abcondas approved these changes
approved but one tiny comment...

2021-02-02 08:04 UTC, janveselynet commented on src/Operator/EqualTo/QueryLanguageFieldSupportingEqualToOperator.php
> +     * @param mixed $value soutput of single value parser
Typo, thanks :-)

2021-02-02 08:19 UTC, merged