DE-31054 Add like symbol operator
BrandEmbassy/query-language-parser pull request #11
Opened 2022-05-17 13:03 UTC by vharnach

2022-05-17 14:35 UTC, michal-tichy-84 requested changes

2022-05-17 14:35 UTC, michal-tichy-84 commented on src/Operator/Like/LikeQueryLanguageOperatorTest.php
> +            ['query' => 'brandLIKE bmw'],
[M] I am pretty sure we do not want to support this

2022-05-18 07:30 UTC, vharnach commented on src/Operator/Like/LikeQueryLanguageOperatorTest.php
> +            ['query' => 'brandLIKE bmw'],
True, I should have used QueryLanguageOperatorParserCreator::createWordOperatorParser for "word operator"

2022-05-18 07:34 UTC, vharnach commented on src/Operator/Like/LikeQueryLanguageOperator.php
> -        return QueryLanguageOperatorParserCreator::createSignOperatorParser('~');
I used the former class for LIKE operator and Like**Symbol**QueryLanguageOperator class for ~

2022-05-18 07:37 UTC, vharnach commented on src/Operator/Like/LikeSymbolQueryLanguageOperator.php
> +class LikeSymbolQueryLanguageOperator implements QueryLanguageOperator
You are right, but to update the whole parser engine to support more than one operator... It does not seem to be worth the effort.

2022-05-18 08:35 UTC, michal-tichy-84 commented on src/Operator/Like/LikeQueryLanguageOperatorTest.php
> +            ['query' => 'brandLIKE bmw'],
So this is a valid scenario?

2022-05-18 09:10 UTC, michal-tichy-84 approved these changes

2022-05-18 09:17 UTC, milan-zelenka approved these changes

2022-05-18 09:17 UTC, milan-zelenka commented on src/Operator/Like/LikeQueryLanguageOperatorTest.php
> +            ['query' => 'brand LIKE bmw'],
[M] What about searching for multiple words, e.g. 'bmw m305' ?

2022-05-18 11:25 UTC, vharnach commented on src/Operator/Like/LikeQueryLanguageOperatorTest.php
> +            ['query' => 'brand LIKE bmw'],
that is not supported by the query language

2022-05-18 11:25 UTC, merged