Added Value-only support
BrandEmbassy/query-language-parser pull request #14
Opened 2023-01-10 11:53 UTC by milan-zelenka

2023-01-12 12:36 UTC, michal-tichy-84 approved these changes

2023-01-12 12:36 UTC, michal-tichy-84 commented on examples/Car/QueryLanguage/CarValueOnlyQueryLanguageField.php
> +    }
[O] Isn't it somehow useless here? Maybe even confusing...

2023-01-12 12:36 UTC, michal-tichy-84 commented on examples/Car/QueryLanguage/CarValueOnlyQueryLanguageField.php
> +    }
Maybe `ValueOnlyQueryLanguageField` should be rather some abstract implementation. By this way, you force implementator to invent some fake idents

2023-01-12 12:39 UTC, milan-zelenka commented on examples/Car/QueryLanguage/CarValueOnlyQueryLanguageField.php
> +    }
Good point, maybe I could make it work without these

2023-01-12 16:57 UTC, janveselynet commented on examples/Car/QueryLanguage/CarValueOnlyQueryLanguageField.php
> +    }
I think it's pretty fine this way, but it shouldn't be field parser, but value parser - you are parsing only value, not field.

2023-01-12 17:00 UTC, janveselynet commented on src/Field/ValueOnlyQueryLanguageField.php
> +interface ValueOnlyQueryLanguageField extends QueryLanguageField
I think this should extend just part of the QueryLanguageField - you don't want to have field parser, I would omit this part.

2023-01-12 17:01 UTC, janveselynet commented on src/Value/ValueOnlyParserCreator.php
> +class ValueOnlyParserCreator
I would allow to wrap the value in quotes and single quotes as well. Maybe using \BrandEmbassy\QueryLanguageParser\Value\TextValueParserCreator instead?

2023-01-12 17:02 UTC, janveselynet requested changes
I would re-work interfaces a bit to make it more transparent and flexible

2023-01-17 15:08 UTC, janveselynet commented on src/Value/ValueOnlyParserCreator.php
> +                TextValueParserCreator::createWithCustomPattern(
Why arent' you using the default regex for the text value parser?

2023-01-17 15:12 UTC, janveselynet commented on src/Value/StringValueParserCreator.php
> +    private const STRING_VALUE_PARSER = '/^[^\s,()=<>~]+/';
Why are you changing this?

2023-01-17 15:16 UTC, janveselynet commented on examples/Car/QueryLanguage/CarQueryParserFactory.php
> +    public function create(bool $useValueOnlyFilter): QueryParser
What about another method instead of using bool parameter?

2023-01-17 15:23 UTC, janveselynet approved these changes
Minor issues only. In the future, I would consider improving it by providing a possibility to define regex for value only value.

2023-01-17 17:17 UTC, michal-tichy-84 commented on src/Value/ValueOnlyParserCreator.php
> +                TextValueParserCreator::createWithCustomPattern(
I would like to exclude only the exact list of forbidden symbols

2023-01-17 17:18 UTC, michal-tichy-84 commented on src/Value/StringValueParserCreator.php
> +    private const STRING_VALUE_PARSER = '/^[^\s,()=<>~]+/';
The same as previous

2023-01-17 17:24 UTC, michal-tichy-84 commented on examples/Car/QueryLanguage/CarQueryParserFactory.php
> +    public function create(bool $useValueOnlyFilter): QueryParser
Yep, right

2023-01-18 13:05 UTC, merged